// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: image_svc.proto

package imageoptimizer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptimizeImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image     []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Scale     bool   `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Greyscale bool   `protobuf:"varint,3,opt,name=greyscale,proto3" json:"greyscale,omitempty"`
}

func (x *OptimizeImageRequest) Reset() {
	*x = OptimizeImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_svc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptimizeImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeImageRequest) ProtoMessage() {}

func (x *OptimizeImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_svc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeImageRequest.ProtoReflect.Descriptor instead.
func (*OptimizeImageRequest) Descriptor() ([]byte, []int) {
	return file_image_svc_proto_rawDescGZIP(), []int{0}
}

func (x *OptimizeImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *OptimizeImageRequest) GetScale() bool {
	if x != nil {
		return x.Scale
	}
	return false
}

func (x *OptimizeImageRequest) GetGreyscale() bool {
	if x != nil {
		return x.Greyscale
	}
	return false
}

type OptimizeImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *OptimizeImageReply) Reset() {
	*x = OptimizeImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_svc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptimizeImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeImageReply) ProtoMessage() {}

func (x *OptimizeImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_image_svc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeImageReply.ProtoReflect.Descriptor instead.
func (*OptimizeImageReply) Descriptor() ([]byte, []int) {
	return file_image_svc_proto_rawDescGZIP(), []int{1}
}

func (x *OptimizeImageReply) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_image_svc_proto protoreflect.FileDescriptor

var file_image_svc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65,
	0x72, 0x22, 0x60, 0x0a, 0x14, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x65, 0x79, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x67, 0x72, 0x65, 0x79, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x32, 0x6d, 0x0a, 0x0e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6d, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x5b, 0x0a, 0x0d, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a,
	0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x24, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x6f, 0x70,
	0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x4f, 0x70,
	0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x69, 0x7a, 0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_image_svc_proto_rawDescOnce sync.Once
	file_image_svc_proto_rawDescData = file_image_svc_proto_rawDesc
)

func file_image_svc_proto_rawDescGZIP() []byte {
	file_image_svc_proto_rawDescOnce.Do(func() {
		file_image_svc_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_svc_proto_rawDescData)
	})
	return file_image_svc_proto_rawDescData
}

var file_image_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_image_svc_proto_goTypes = []interface{}{
	(*OptimizeImageRequest)(nil), // 0: imageoptimizer.OptimizeImageRequest
	(*OptimizeImageReply)(nil),   // 1: imageoptimizer.OptimizeImageReply
}
var file_image_svc_proto_depIdxs = []int32{
	0, // 0: imageoptimizer.ImageOptimizer.OptimizeImage:input_type -> imageoptimizer.OptimizeImageRequest
	1, // 1: imageoptimizer.ImageOptimizer.OptimizeImage:output_type -> imageoptimizer.OptimizeImageReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_svc_proto_init() }
func file_image_svc_proto_init() {
	if File_image_svc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_image_svc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptimizeImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_svc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptimizeImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_svc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_svc_proto_goTypes,
		DependencyIndexes: file_image_svc_proto_depIdxs,
		MessageInfos:      file_image_svc_proto_msgTypes,
	}.Build()
	File_image_svc_proto = out.File
	file_image_svc_proto_rawDesc = nil
	file_image_svc_proto_goTypes = nil
	file_image_svc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImageOptimizerClient is the client API for ImageOptimizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImageOptimizerClient interface {
	OptimizeImage(ctx context.Context, in *OptimizeImageRequest, opts ...grpc.CallOption) (*OptimizeImageReply, error)
}

type imageOptimizerClient struct {
	cc *grpc.ClientConn
}

func NewImageOptimizerClient(cc *grpc.ClientConn) ImageOptimizerClient {
	return &imageOptimizerClient{cc}
}

func (c *imageOptimizerClient) OptimizeImage(ctx context.Context, in *OptimizeImageRequest, opts ...grpc.CallOption) (*OptimizeImageReply, error) {
	out := new(OptimizeImageReply)
	err := c.cc.Invoke(ctx, "/imageoptimizer.ImageOptimizer/OptimizeImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageOptimizerServer is the server API for ImageOptimizer service.
type ImageOptimizerServer interface {
	OptimizeImage(context.Context, *OptimizeImageRequest) (*OptimizeImageReply, error)
}

// UnimplementedImageOptimizerServer can be embedded to have forward compatible implementations.
type UnimplementedImageOptimizerServer struct {
}

func (*UnimplementedImageOptimizerServer) OptimizeImage(context.Context, *OptimizeImageRequest) (*OptimizeImageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptimizeImage not implemented")
}

func RegisterImageOptimizerServer(s *grpc.Server, srv ImageOptimizerServer) {
	s.RegisterService(&_ImageOptimizer_serviceDesc, srv)
}

func _ImageOptimizer_OptimizeImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageOptimizerServer).OptimizeImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imageoptimizer.ImageOptimizer/OptimizeImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageOptimizerServer).OptimizeImage(ctx, req.(*OptimizeImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImageOptimizer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imageoptimizer.ImageOptimizer",
	HandlerType: (*ImageOptimizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OptimizeImage",
			Handler:    _ImageOptimizer_OptimizeImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "image_svc.proto",
}
